def size = 100 / 2
def corner = 0.6

#Main Shape
line(size * corner (-1 * size) (-1 * size * corner) (-1 * size))
line(size size * corner size (-1 * size * corner))
line((-1 * size * corner) size size * corner size )
line((-1 * size) size * corner (-1 * size) (-1 * size * corner))

#Corner lines
line(size * corner (-1 * size) size (-1 * size * corner))
line(size size * corner size * corner size)
line((-1 * size * corner) size (-1 * size) size * corner)
line((-1 * size) (-1 * size * corner) (-1 * size * corner) (-1 * size))

#Motor Screws
circle(size - 4 9 0.75)
circle(size - 4 -9 0.75)

circle(-1 * size - 4 9 0.75)
circle(-1 * size - 4 -9 0.75)

#Caster Mount
circle(7.5 -1 * size - 10 0.75)
circle(-7.5 -1 * size - 10 0.75)
circle(0 -1 * size - 10 7.5)

#Standoffs
circle(size - 10 (size * corner) - 5 1.75)
circle(-1 * size - 10 (size * corner) - 5 1.75)
circle((size * corner) - 5 -1 * size - 10 1.75)
circle((-1 * size * corner) + 5 -1 * size - 10 1.75)

#Battery Holder
line(-29 -31 29 -31)
line(-29 -31 -29 31)
line(-29 31 29 31)
line(29 -31 29 31)
circle(0 28.5 1.5)
circle(0 -28.5 1.5)