import boxPlate

#FUNCTION MAKEBOX:
#a function to draw five plates to make up a storage box
#ready for printing on a laser cutter

def makeBox(width as Number height as Number depth as Number) = {
 
  def holeRadius = 2
  def partSpacing = 10

  #BOTTOM
  plate(width depth 0 0 holeRadius 0)

  #FRONT
  plate(width height 0 (0 - height) - partSpacing holeRadius 1)
 
  #BACK
  plate(width height 0 depth + partSpacing holeRadius 0)
  
  #SIDE1
  plate(height depth partSpacing + width 0 holeRadius 0)
  
  #SIDE2
  def offsetX = 0 - height
  plate(height depth offsetX - partSpacing 0 holeRadius 0)

}

makeBox(210 210 380)